- name: Copy LDAP-Client config
  template:
    src: ldap.conf
    dest: /etc/ldap/ldap.conf
    owner: root
    group: root
    mode: 0644

- name: Copy certificate for LDAP
  copy:
    src: ldapCA.pem
    dest: /etc/ssl/ldapCA.pem
    owner: root
    group: root
    mode: 0644